-- =============================================
-- MedQuest: Gamified YLL Revision Platform
-- Supabase Schema
-- =============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- AUTH & USERS
-- =============================================

-- User profiles (extends Supabase auth.users)
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  display_name TEXT,
  matric_number TEXT,
  avatar_url TEXT,
  is_whitelisted BOOLEAN DEFAULT FALSE,
  is_admin BOOLEAN DEFAULT FALSE,
  
  -- Gamification
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  streak_current INTEGER DEFAULT 0,
  streak_longest INTEGER DEFAULT 0,
  streak_last_activity DATE,
  
  -- Stats
  questions_answered INTEGER DEFAULT 0,
  questions_correct INTEGER DEFAULT 0,
  total_study_time_minutes INTEGER DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Email whitelist (for non-NUS emails you want to allow)
CREATE TABLE email_whitelist (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT UNIQUE NOT NULL,
  added_by UUID REFERENCES profiles(id),
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- QUESTION BANK
-- =============================================

-- Systems taxonomy
CREATE TYPE question_system AS ENUM (
  'Foundation',
  'Blood',
  'Cardiovascular',
  'Renal', 
  'Respiratory',
  'Gastrointestinal',
  'Metabolism',
  'Immunology',
  'Pharmacology',
  'Pathology',
  'Mixed'
);

-- Question types
CREATE TYPE question_type AS ENUM ('MCQ', 'MEQ');

-- Difficulty tiers (matching YLL structure)
CREATE TYPE difficulty_tier AS ENUM (
  'Tier1_Recall',        -- 20% of YLL exams
  'Tier2_Application',   -- 50% of YLL exams
  'Tier3_Integration'    -- 30% of YLL exams
);

-- Question source
CREATE TYPE question_source AS ENUM (
  'PYP_Extracted',    -- Directly from past year papers
  'AI_Generated',     -- Generated by Claude based on PYP style + Anki
  'Recall_Derived',   -- Derived from student recalls
  'Manual'            -- Manually added
);

-- Main questions table
CREATE TABLE questions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Content
  question_type question_type NOT NULL DEFAULT 'MCQ',
  system question_system NOT NULL,
  topic TEXT NOT NULL,               -- e.g. "Glomerulonephritis", "MI Mechanism"
  subtopic TEXT,                     -- e.g. "IgA Nephropathy", "STEMI"
  
  -- Question body
  vignette TEXT,                     -- Clinical scenario (may be null for pure recall Qs)
  question_text TEXT NOT NULL,       -- The actual question
  image_url TEXT,                    -- For histology slides, X-rays, ECGs
  image_caption TEXT,
  
  -- MCQ options (stored as JSONB array)
  -- Format: [{"id": "A", "text": "..."}, {"id": "B", "text": "..."}, ...]
  options JSONB,                     -- NULL for MEQ
  correct_option TEXT,               -- "A"-"E" for MCQ, NULL for MEQ
  
  -- MEQ answer (for MEQ type)
  meq_model_answer TEXT,
  meq_marking_points JSONB,          -- [{"point": "...", "marks": 1}, ...]
  meq_total_marks INTEGER,
  
  -- Explanation (shown after answering)
  explanation TEXT NOT NULL,
  explanation_mechanism TEXT,        -- The "why" — mechanism-focused
  high_yield_pearl TEXT,            -- The one-liner to remember
  
  -- Metadata
  difficulty difficulty_tier NOT NULL DEFAULT 'Tier2_Application',
  source question_source NOT NULL DEFAULT 'PYP_Extracted',
  source_paper TEXT,                 -- e.g. "Phase I EOY 2023"
  source_year INTEGER,
  tags TEXT[],                       -- ['ECG', 'Pharmacology', 'Coagulation']
  
  -- High-yield scoring
  pyp_frequency INTEGER DEFAULT 1,   -- How many times this concept appeared in PYPs
  high_yield_score FLOAT GENERATED ALWAYS AS (
    CASE 
      WHEN difficulty = 'Tier2_Application' THEN pyp_frequency * 1.5
      WHEN difficulty = 'Tier3_Integration' THEN pyp_frequency * 2.0
      ELSE pyp_frequency * 1.0
    END
  ) STORED,
  
  -- Quality control
  is_verified BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  flagged_count INTEGER DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- USER PERFORMANCE TRACKING
-- =============================================

-- Every answer attempt
CREATE TABLE answer_attempts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  question_id UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  
  -- Answer
  selected_option TEXT,              -- MCQ: "A"-"E"
  meq_answer TEXT,                   -- MEQ: free text
  is_correct BOOLEAN,
  time_taken_seconds INTEGER,
  
  -- Session context
  session_type TEXT,                 -- 'practice', 'timed', 'daily_rounds', 'boss_battle'
  
  -- XP awarded
  xp_earned INTEGER DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Per-topic mastery tracking
CREATE TABLE topic_mastery (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  system question_system NOT NULL,
  topic TEXT NOT NULL,
  
  -- Mastery metrics
  attempts INTEGER DEFAULT 0,
  correct INTEGER DEFAULT 0,
  mastery_score FLOAT DEFAULT 0.0,   -- 0.0-1.0, computed
  mastery_level TEXT DEFAULT 'unstarted', -- unstarted, learning, familiar, mastered
  
  -- Spaced repetition
  next_review_date DATE,
  ease_factor FLOAT DEFAULT 2.5,     -- SM-2 algorithm
  interval_days INTEGER DEFAULT 1,
  
  last_attempted TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(user_id, system, topic)
);

-- =============================================
-- GAMIFICATION
-- =============================================

-- Badge definitions
CREATE TABLE badges (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  icon TEXT NOT NULL,                -- emoji or icon name
  condition_type TEXT NOT NULL,      -- 'streak', 'xp', 'accuracy', 'topic_mastered', 'questions_answered'
  condition_value INTEGER NOT NULL,
  condition_system question_system,  -- NULL = any system
  xp_reward INTEGER DEFAULT 50,
  rarity TEXT DEFAULT 'common'       -- common, rare, epic, legendary
);

-- User earned badges
CREATE TABLE user_badges (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  badge_id UUID NOT NULL REFERENCES badges(id),
  earned_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, badge_id)
);

-- XP transaction log (audit trail)
CREATE TABLE xp_transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  amount INTEGER NOT NULL,
  reason TEXT NOT NULL,              -- 'correct_answer', 'streak_bonus', 'badge_earned', etc.
  reference_id UUID,                 -- attempt ID, badge ID, etc.
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Daily study sessions
CREATE TABLE study_sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  session_type TEXT NOT NULL,        -- 'practice', 'timed', 'daily_rounds', 'boss_battle'
  system_focus question_system,
  questions_total INTEGER DEFAULT 0,
  questions_correct INTEGER DEFAULT 0,
  xp_earned INTEGER DEFAULT 0,
  duration_minutes INTEGER DEFAULT 0,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- Question flags (for reporting errors)
CREATE TABLE question_flags (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  question_id UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  details TEXT,
  resolved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- DAILY RECOMMENDATIONS
-- =============================================

-- Daily "Grand Rounds" recommendation (pre-computed)
CREATE TABLE daily_recommendations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  recommendation_date DATE NOT NULL DEFAULT CURRENT_DATE,
  question_ids UUID[] NOT NULL,      -- Ordered list of 10 recommended questions
  rationale JSONB,                   -- {"renal": 4, "cvs": 3, "blood": 3} -- why these?
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, recommendation_date)
);

-- =============================================
-- LEADERBOARD VIEW
-- =============================================

CREATE VIEW leaderboard AS
SELECT 
  p.id,
  p.display_name,
  p.xp,
  p.level,
  p.streak_current,
  p.questions_answered,
  CASE 
    WHEN p.questions_answered > 0 
    THEN ROUND((p.questions_correct::NUMERIC / p.questions_answered) * 100, 1)
    ELSE 0 
  END AS accuracy_percent,
  RANK() OVER (ORDER BY p.xp DESC) AS rank
FROM profiles p
WHERE p.is_whitelisted = TRUE OR p.email LIKE '%@u.nus.edu'
ORDER BY p.xp DESC;

-- =============================================
-- SEED: DEFAULT BADGES
-- =============================================

INSERT INTO badges (name, description, icon, condition_type, condition_value, xp_reward, rarity) VALUES
('First Blood', 'Answer your first question', '🩸', 'questions_answered', 1, 25, 'common'),
('On a Roll', 'Get 5 correct in a row', '🔥', 'streak', 5, 50, 'common'),
('Week Warrior', '7-day study streak', '📅', 'streak', 7, 100, 'rare'),
('Century Club', 'Answer 100 questions', '💯', 'questions_answered', 100, 150, 'rare'),
('Renal God', 'Master all Renal topics', '🧪', 'topic_mastered', 1, 200, 'epic'),
('Cardio King', 'Master all CVS topics', '🫀', 'topic_mastered', 1, 200, 'epic'),
('High Yield Hunter', 'Answer 50 high-yield questions correctly', '🎯', 'questions_answered', 50, 150, 'rare'),
('Speed Demon', 'Complete a timed set in under 10 minutes', '⚡', 'accuracy', 1, 100, 'rare'),
('The Consultant', 'Reach Level 20', '🏥', 'xp', 5000, 500, 'legendary'),
('Accuracy Ace', 'Maintain 90%+ accuracy over 50 questions', '🎯', 'accuracy', 90, 300, 'epic');

-- =============================================
-- ROW LEVEL SECURITY
-- =============================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE answer_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE topic_mastery ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE xp_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_recommendations ENABLE ROW LEVEL SECURITY;

-- Profiles: users see their own, leaderboard sees all
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can upsert own profile" ON profiles FOR ALL USING (auth.uid() = id);

-- Answer attempts: own only
CREATE POLICY "Users manage own attempts" ON answer_attempts FOR ALL USING (auth.uid() = user_id);

-- Topic mastery: own only
CREATE POLICY "Users manage own mastery" ON topic_mastery FOR ALL USING (auth.uid() = user_id);

-- User badges: own view
CREATE POLICY "Users view own badges" ON user_badges FOR SELECT USING (auth.uid() = user_id);

-- XP: own view
CREATE POLICY "Users view own XP" ON xp_transactions FOR SELECT USING (auth.uid() = user_id);

-- Study sessions: own
CREATE POLICY "Users manage own sessions" ON study_sessions FOR ALL USING (auth.uid() = user_id);

-- Daily recs: own
CREATE POLICY "Users manage own recommendations" ON daily_recommendations FOR ALL USING (auth.uid() = user_id);

-- Questions: all authenticated users can read active questions
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users read questions" ON questions FOR SELECT TO authenticated USING (is_active = TRUE);
CREATE POLICY "Admins manage questions" ON questions FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = TRUE)
);

-- =============================================
-- FUNCTIONS
-- =============================================

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER questions_updated_at BEFORE UPDATE ON questions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER topic_mastery_updated_at BEFORE UPDATE ON topic_mastery FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Compute mastery score after each attempt
CREATE OR REPLACE FUNCTION update_topic_mastery()
RETURNS TRIGGER AS $$
DECLARE
  q_system question_system;
  q_topic TEXT;
BEGIN
  SELECT system, topic INTO q_system, q_topic FROM questions WHERE id = NEW.question_id;
  
  INSERT INTO topic_mastery (user_id, system, topic, attempts, correct, mastery_score, mastery_level, last_attempted)
  VALUES (
    NEW.user_id, q_system, q_topic, 1,
    CASE WHEN NEW.is_correct THEN 1 ELSE 0 END,
    CASE WHEN NEW.is_correct THEN 0.5 ELSE 0.1 END,
    CASE WHEN NEW.is_correct THEN 'learning' ELSE 'unstarted' END,
    NOW()
  )
  ON CONFLICT (user_id, system, topic) DO UPDATE SET
    attempts = topic_mastery.attempts + 1,
    correct = topic_mastery.correct + CASE WHEN NEW.is_correct THEN 1 ELSE 0 END,
    mastery_score = LEAST(1.0, (topic_mastery.correct + CASE WHEN NEW.is_correct THEN 1 ELSE 0 END)::FLOAT / (topic_mastery.attempts + 1)),
    mastery_level = CASE
      WHEN (topic_mastery.correct + CASE WHEN NEW.is_correct THEN 1 ELSE 0 END)::FLOAT / (topic_mastery.attempts + 1) >= 0.85 THEN 'mastered'
      WHEN (topic_mastery.correct + CASE WHEN NEW.is_correct THEN 1 ELSE 0 END)::FLOAT / (topic_mastery.attempts + 1) >= 0.6 THEN 'familiar'
      WHEN topic_mastery.attempts + 1 > 0 THEN 'learning'
      ELSE 'unstarted'
    END,
    last_attempted = NOW(),
    updated_at = NOW();
    
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_answer_attempt 
AFTER INSERT ON answer_attempts 
FOR EACH ROW EXECUTE FUNCTION update_topic_mastery();

-- Award XP after correct answer
CREATE OR REPLACE FUNCTION award_xp_for_attempt()
RETURNS TRIGGER AS $$
DECLARE
  xp_amount INTEGER;
  q_difficulty difficulty_tier;
BEGIN
  IF NOT NEW.is_correct THEN RETURN NEW; END IF;
  
  SELECT difficulty INTO q_difficulty FROM questions WHERE id = NEW.question_id;
  
  xp_amount := CASE q_difficulty
    WHEN 'Tier1_Recall' THEN 10
    WHEN 'Tier2_Application' THEN 20
    WHEN 'Tier3_Integration' THEN 35
    ELSE 10
  END;
  
  -- Speed bonus
  IF NEW.time_taken_seconds IS NOT NULL AND NEW.time_taken_seconds < 30 THEN
    xp_amount := xp_amount + 5;
  END IF;
  
  UPDATE NEW SET xp_earned = xp_amount;
  
  UPDATE profiles SET 
    xp = xp + xp_amount,
    questions_answered = questions_answered + 1,
    questions_correct = questions_correct + 1,
    level = GREATEST(1, FLOOR(SQRT(xp / 100)) + 1)
  WHERE id = NEW.user_id;
  
  INSERT INTO xp_transactions (user_id, amount, reason, reference_id)
  VALUES (NEW.user_id, xp_amount, 'correct_answer', NEW.id);
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Update wrong answer stats too
CREATE OR REPLACE FUNCTION update_profile_stats()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE profiles SET 
    questions_answered = questions_answered + 1
  WHERE id = NEW.user_id AND NOT NEW.is_correct;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_answer_xp AFTER INSERT ON answer_attempts FOR EACH ROW EXECUTE FUNCTION award_xp_for_attempt();
CREATE TRIGGER after_answer_stats AFTER INSERT ON answer_attempts FOR EACH ROW WHEN (NOT NEW.is_correct) EXECUTE FUNCTION update_profile_stats();
